### ISSUE TITLE
Add language code as the outer-most level

### ISSUE THREAD

**Issue by aaronsnig501** [decyphr-net/i18nr#48]
Frameworks like Rails require a top-level language code, even file name is already using that code:

```yaml
en:
  activerecord:
    models:
      feedback: "Feedback"
```
